package com.suprememc.content

import com.google.gson.JsonObject
import com.google.gson.JsonParser
import org.junit.jupiter.api.Test
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class FloridaPlainsDataTest : GeneratedDataTestSupport() {
    // Biome definitions and the mixed-tree configured feature are hand-authored under common's static
    // resources (same convention as palm.json/palm_coconut.json); placed features are generated into
    // neoforge/src/generated by FloridaPlainsDataProvider.
    private val commonWorldgen = Path.of("..", "common", "src", "main", "resources", "data", "suprememc", "worldgen")

    private fun readStaticJson(relative: String): JsonObject =
        JsonParser.parseString(Files.readString(commonWorldgen.resolve(relative))).asJsonObject

    @Test
    fun biomeIsHotFlatAndJungleTintedWithSwampWater() {
        val biome = readStaticJson("biome/florida_plains.json")
        assertEquals(0.9F, biome.get("temperature").asFloat)
        val effects = biome.getAsJsonObject("effects")
        assertEquals("#617b64", effects.get("water_color").asString)
        assertEquals("#59c93c", effects.get("grass_color").asString)
        assertFalse(effects.has("grass_color_modifier"))
        assertEquals("#30bb0b", effects.get("foliage_color").asString)
        // Less humid/waterlogged than vanilla swamp's downfall of 0.9.
        assertTrue(biome.get("downfall").asFloat < 0.9F)
    }

    @Test
    fun biomeSharesSwampSpawnersAndSwampFoliagePatches() {
        val biome = readStaticJson("biome/florida_plains.json")
        val monsters = biome.getAsJsonObject("spawners").getAsJsonArray("monster").map { it.asJsonObject.get("type").asString }
        assertTrue(listOf("minecraft:witch", "minecraft:bogged", "minecraft:slime").all { it in monsters })
        assertTrue(biome.getAsJsonObject("spawners").getAsJsonArray("creature").any { it.asJsonObject.get("type").asString == "minecraft:frog" })

        val vegetationEntries = biome.getAsJsonArray("features")[9].asJsonArray.map { it.asString }
        assertTrue("minecraft:flower_swamp" in vegetationEntries)
        assertTrue("minecraft:patch_grass_normal" in vegetationEntries)
        assertTrue("suprememc:florida_plains_trees" in vegetationEntries)
        assertTrue("suprememc:tomato_bushes" in vegetationEntries)
        assertFalse("minecraft:trees_swamp" in vegetationEntries)
        assertFalse("minecraft:patch_waterlily" in vegetationEntries)
    }

    @Test
    fun caysHaveNoHostileMobSpawnsOrMonsterRooms() {
        val biome = readStaticJson("biome/cays.json")
        val spawners = biome.getAsJsonObject("spawners")
        assertTrue(spawners.getAsJsonArray("monster").isEmpty)

        val undergroundFeatures = biome.getAsJsonArray("features")[3].asJsonArray.map { it.asString }
        assertFalse("minecraft:monster_room" in undergroundFeatures)
        assertFalse("minecraft:monster_room_deep" in undergroundFeatures)
    }

    @Test
    fun tomatoPatchesPlaceFullyGrownBushes() {
        val configured = readJson("data/suprememc/worldgen/configured_feature/tomato_bushes.json")
        assertEquals("minecraft:simple_block", configured.get("type").asString)
        val state = configured.getAsJsonObject("config").getAsJsonObject("to_place")
            .getAsJsonObject("state")
        assertEquals("suprememc:tomato_bush", state.get("Name").asString)
        assertEquals("3", state.getAsJsonObject("Properties").get("age").asString)

        val placed = readJson("data/suprememc/worldgen/placed_feature/tomato_bushes.json")
        assertEquals("suprememc:tomato_bushes", placed.get("feature").asString)
    }

    @Test
    fun mixedTreeFeatureSplitsPalmSwampOakAndJungleBushRoughlyEvenly() {
        val trees = readStaticJson("configured_feature/florida_plains_trees.json")
        assertEquals("minecraft:random_selector", trees.get("type").asString)
        val config = trees.getAsJsonObject("config")
        assertEquals("minecraft:jungle_bush", config.get("default").asString)
        val entries = config.getAsJsonArray("features").map { it.asJsonObject }
        // "feature" here is a placed_feature reference (RandomFeatureConfiguration), so bare wrappers are used.
        assertTrue(entries.any { it.get("feature").asString == "suprememc:palm_coconut_bare" })
        assertTrue(entries.any { it.get("feature").asString == "suprememc:swamp_oak_bare" })
    }

    @Test
    fun barePlacedFeatureWrappersAreGeneratedForRandomSelectorEntries() {
        // random_selector entries bind to placed features, so datagen emits placement-free wrappers
        // that the hand-authored florida_plains_trees configured feature references.
        val palmBare = readJson("data/suprememc/worldgen/placed_feature/palm_coconut_bare.json")
        assertEquals("suprememc:palm_coconut", palmBare.get("feature").asString)
        assertEquals(0, palmBare.getAsJsonArray("placement").size())

        val swampOakBare = readJson("data/suprememc/worldgen/placed_feature/swamp_oak_bare.json")
        assertEquals("minecraft:swamp_oak", swampOakBare.get("feature").asString)
        assertEquals(0, swampOakBare.getAsJsonArray("placement").size())
    }

    @Test
    fun witchHutsCanSpawnHereViaAdditiveBiomeTag() {
        val tag = readJson("data/minecraft/tags/worldgen/biome/has_structure/swamp_hut.json")
        assertEquals(listOf("suprememc:florida_plains"), tag.getAsJsonArray("values").map { it.asString })
    }

    @Test
    fun treesPlacementMirrorsVanillaSwampTreeDensity() {
        val placed = readJson("data/suprememc/worldgen/placed_feature/florida_plains_trees.json")
        assertEquals("suprememc:florida_plains_trees", placed.get("feature").asString)
        val placements = placed.getAsJsonArray("placement").map { it.asJsonObject }
        val count = placements.first { it.get("type").asString == "minecraft:count" }.getAsJsonObject("count")
        val distribution = count.getAsJsonArray("distribution").map { it.asJsonObject }
        assertEquals(listOf(2 to 9, 3 to 1), distribution.map { it.get("data").asInt to it.get("weight").asInt })
        assertEquals(2, placements.first { it.get("type").asString == "minecraft:surface_water_depth_filter" }.get("max_water_depth").asInt)
    }
}
