package com.suprememc.tabs;

import com.suprememc.content.ModContent;
import com.suprememc.content.init.ModBlockItems;
import com.suprememc.content.init.ModFoods;
import com.suprememc.content.init.ModItems;

import java.util.List;

public final class CreativeTab {

	private CreativeTab() {
	}

	public static void populate() {
		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModContent.PALM_LOG, ModContent.STRIPPED_PALM_LOG, ModContent.PALM_WOOD, ModContent.STRIPPED_PALM_WOOD,
			ModContent.LAVENDER_ENDSPAR, ModContent.LAVENDER_ROOTS, ModContent.LAVENDER_FUNGUS,
			ModContent.LAVENDER_STEM, ModContent.STRIPPED_LAVENDER_STEM,
			ModContent.LAVENDER_HYPHAE, ModContent.STRIPPED_LAVENDER_HYPHAE,
			ModContent.LAVENDER_WOOD, ModContent.STRIPPED_LAVENDER_WOOD,
			ModContent.LAVENDER_PLANKS, ModContent.LAVENDER_STAIRS, ModContent.LAVENDER_SLAB,
			ModContent.LAVENDER_FENCE, ModContent.LAVENDER_FENCE_GATE, ModContent.LAVENDER_DOOR,
			ModContent.LAVENDER_TRAPDOOR, ModContent.LAVENDER_PRESSURE_PLATE, ModContent.LAVENDER_BUTTON,
			ModContent.LAVENDER_SIGN, ModContent.LAVENDER_HANGING_SIGN,
			ModContent.PALM_PLANKS, ModContent.PALM_STAIRS, ModContent.PALM_SLAB, ModContent.PALM_FENCE, ModContent.PALM_FENCE_GATE,
			ModContent.PALM_DOOR, ModContent.PALM_TRAPDOOR, ModContent.PALM_PRESSURE_PLATE, ModContent.PALM_BUTTON,
			ModContent.PALM_SIGN, ModContent.PALM_HANGING_SIGN
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModContent.SPRUCE_BOOKSHELF, ModContent.BIRCH_BOOKSHELF, ModContent.JUNGLE_BOOKSHELF,
			ModContent.ACACIA_BOOKSHELF, ModContent.DARK_OAK_BOOKSHELF, ModContent.MANGROVE_BOOKSHELF,
			ModContent.CHERRY_BOOKSHELF, ModContent.PALE_OAK_BOOKSHELF, ModContent.BAMBOO_BOOKSHELF,
			ModContent.CRIMSON_BOOKSHELF, ModContent.WARPED_BOOKSHELF, ModContent.PALM_BOOKSHELF, ModContent.LAVENDER_BOOKSHELF,
			ModContent.SPRUCE_CRAFTING_TABLE, ModContent.BIRCH_CRAFTING_TABLE, ModContent.JUNGLE_CRAFTING_TABLE,
			ModContent.ACACIA_CRAFTING_TABLE, ModContent.DARK_OAK_CRAFTING_TABLE, ModContent.MANGROVE_CRAFTING_TABLE,
			ModContent.CHERRY_CRAFTING_TABLE, ModContent.PALE_OAK_CRAFTING_TABLE, ModContent.BAMBOO_CRAFTING_TABLE,
			ModContent.CRIMSON_CRAFTING_TABLE, ModContent.WARPED_CRAFTING_TABLE, ModContent.PALM_CRAFTING_TABLE, ModContent.LAVENDER_CRAFTING_TABLE,
			ModContent.BLACKSTONE_FURNACE, ModContent.DEEPSLATE_FURNACE,
			ModContent.COAL_STAIRS, ModContent.COAL_SLAB,
			ModContent.POLISHED_GRANITE_WALL, ModContent.POLISHED_DIORITE_WALL, ModContent.POLISHED_ANDESITE_WALL,
			ModContent.ANDESITE_BRICKS, ModContent.ANDESITE_BRICK_STAIRS, ModContent.ANDESITE_BRICK_SLAB, ModContent.ANDESITE_BRICK_WALL,
			ModContent.DIORITE_BRICKS, ModContent.DIORITE_BRICK_STAIRS, ModContent.DIORITE_BRICK_SLAB, ModContent.DIORITE_BRICK_WALL,
			ModContent.GRANITE_BRICKS, ModContent.GRANITE_BRICK_STAIRS, ModContent.GRANITE_BRICK_SLAB, ModContent.GRANITE_BRICK_WALL,
			ModContent.IRON_STAIRS, ModContent.IRON_SLAB,
			ModContent.GOLD_STAIRS, ModContent.GOLD_SLAB,
			ModContent.LAPIS_STAIRS, ModContent.LAPIS_SLAB,
			ModContent.EMERALD_STAIRS, ModContent.EMERALD_SLAB,
			ModContent.DIAMOND_STAIRS, ModContent.DIAMOND_SLAB,
			ModContent.NETHERITE_STAIRS, ModContent.NETHERITE_SLAB,
			ModContent.OBSIDIAN_STAIRS, ModContent.OBSIDIAN_SLAB,
			ModContent.AQUAMARINE_STAIRS, ModContent.AQUAMARINE_SLAB,
			ModContent.AMBER_STAIRS, ModContent.AMBER_SLAB,
			ModContent.BURNING_DIAMOND_STAIRS, ModContent.BURNING_DIAMOND_SLAB,
			ModContent.ABYSSALITE_STAIRS, ModContent.ABYSSALITE_SLAB
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(ModContent.GLOW_BLOCKS.values());
		ModContent.CREATIVE_TAB_ITEMS.addAll(ModContent.SLIME_BLOCKS.values());

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModContent.AQUAMARINE_ORE, ModContent.DEEPSLATE_AQUAMARINE_ORE, ModContent.AQUAMARINE_BLOCK,
			ModContent.BURNING_DIAMOND_ORE, ModContent.BURNING_DIAMOND_BLOCK,
			ModContent.AMBER_ORE, ModContent.DEEPSLATE_AMBER_ORE, ModContent.AMBER_BLOCK,
			ModContent.NETHER_ANTHRACITE_ORE, ModContent.ANTHRACITE_BLOCK,
			ModContent.ATLANTIS_DEBRIS, ModContent.ABYSSALITE_BLOCK, ModContent.LAVENDER_WART_BLOCK,
			ModContent.SUPREME_MC_LOGO_BLOCK,
			ModContent.SNOW_TNT, ModContent.FIRE_TNT,
			ModContent.WET_FARMLAND, ModContent.ICICLE,
			ModContent.PALM_LEAVES, ModContent.PALM_SAPLING,
			ModContent.BEACH_GRASS, ModContent.TALL_BEACH_GRASS,
			ModContent.BUTTERCUP, ModContent.CLOVER
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModBlockItems.COCONUT_SEEDS, ModFoods.COCONUT_ITEM,
			ModBlockItems.COTTON, ModFoods.TOMATO, ModFoods.CORN, ModFoods.GRAPES,
			ModFoods.CALAMARI, ModFoods.COOKED_CALAMARI
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.PALM_BOAT, ModItems.PALM_CHEST_BOAT,
			ModItems.LAVENDER_BOAT, ModItems.LAVENDER_CHEST_BOAT,
			ModItems.GRIZZLY_BEAR_SPAWN_EGG, ModItems.ENDER_SPIDER_SPAWN_EGG,
			ModItems.FIRE_CREEPER_SPAWN_EGG, ModItems.SNOW_CREEPER_SPAWN_EGG
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.BURNING_DIAMOND,
			ModItems.AQUAMARINE,
			ModItems.AMBER,
			ModItems.ANTHRACITE,
			ModItems.EXPERIENCE_DUST, ModItems.XYLIUM_DUST,
			ModItems.EXPERIENCE_INGOT, ModItems.EXPERIENCE_UPGRADE_SMITHING_TEMPLATE,
			ModItems.ABYSSALITE_SCRAP, ModItems.ABYSSALITE_INGOT,
			ModItems.ABYSSALITE_UPGRADE_SMITHING_TEMPLATE
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.BURNING_DIAMOND_SWORD, ModItems.BURNING_DIAMOND_PICKAXE, ModItems.BURNING_DIAMOND_AXE,
			ModItems.BURNING_DIAMOND_SHOVEL, ModItems.BURNING_DIAMOND_HOE,
			ModItems.BURNING_DIAMOND_HELMET, ModItems.BURNING_DIAMOND_CHESTPLATE,
			ModItems.BURNING_DIAMOND_LEGGINGS, ModItems.BURNING_DIAMOND_BOOTS
		));

			ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
				ModItems.BURNING_NETHERITE_SWORD, ModItems.BURNING_NETHERITE_PICKAXE, ModItems.BURNING_NETHERITE_AXE,
				ModItems.BURNING_NETHERITE_SHOVEL, ModItems.BURNING_NETHERITE_HOE,
				ModItems.BURNING_NETHERITE_HELMET, ModItems.BURNING_NETHERITE_CHESTPLATE,
				ModItems.BURNING_NETHERITE_LEGGINGS, ModItems.BURNING_NETHERITE_BOOTS
			));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.AQUAMARINE_SWORD, ModItems.AQUAMARINE_PICKAXE, ModItems.AQUAMARINE_AXE,
			ModItems.AQUAMARINE_SHOVEL, ModItems.AQUAMARINE_HOE,
			ModItems.AQUAMARINE_HELMET, ModItems.AQUAMARINE_CHESTPLATE,
			ModItems.AQUAMARINE_LEGGINGS, ModItems.AQUAMARINE_BOOTS
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.COTTON_HELMET, ModItems.COTTON_CHESTPLATE,
			ModItems.COTTON_LEGGINGS, ModItems.COTTON_BOOTS
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.AMBER_SWORD, ModItems.AMBER_PICKAXE, ModItems.AMBER_AXE,
			ModItems.AMBER_SHOVEL, ModItems.AMBER_HOE,
			ModItems.AMBER_HELMET, ModItems.AMBER_CHESTPLATE,
			ModItems.AMBER_LEGGINGS, ModItems.AMBER_BOOTS
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.EMERALD_SWORD, ModItems.EMERALD_PICKAXE, ModItems.EMERALD_AXE,
			ModItems.EMERALD_SHOVEL, ModItems.EMERALD_HOE,
			ModItems.EMERALD_HELMET, ModItems.EMERALD_CHESTPLATE,
			ModItems.EMERALD_LEGGINGS, ModItems.EMERALD_BOOTS
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.EXPERIENCE_SWORD, ModItems.EXPERIENCE_PICKAXE, ModItems.EXPERIENCE_AXE,
			ModItems.EXPERIENCE_SHOVEL, ModItems.EXPERIENCE_HOE,
			ModItems.EXPERIENCE_HELMET, ModItems.EXPERIENCE_CHESTPLATE,
			ModItems.EXPERIENCE_LEGGINGS, ModItems.EXPERIENCE_BOOTS
		));

		ModContent.CREATIVE_TAB_ITEMS.addAll(List.of(
			ModItems.ABYSSALITE_SWORD, ModItems.ABYSSALITE_TRIDENT, ModItems.ABYSSALITE_PICKAXE,
			ModItems.ABYSSALITE_AXE, ModItems.ABYSSALITE_SHOVEL, ModItems.ABYSSALITE_HOE,
			ModItems.ABYSSALITE_HELMET, ModItems.ABYSSALITE_CHESTPLATE,
			ModItems.ABYSSALITE_LEGGINGS, ModItems.ABYSSALITE_BOOTS
		));
	}
}
